### ISSUE TITLE
adding modules to Ansible  

### ISSUE THREAD

**Issue by mac0815** [sachaboudjema/ansible-modules-arubaos#1]
Hi Sacha
tried to add your modules to Ansible following this Guide
https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html
cloned the Git repo to /usr/share/ansible/plugins/modules/
and validated the function like described on Ansible with
ansible-doc -t module  arubaos_get
but get the error
ERROR! module arubaos_get missing documentation (or could not parse documentation): unknown doc_fragment(s) in file /usr/share/ansible/plugins/modules/ansible-modules-arubaos/library/arubaos_get.py: arubaos

where can i find the requested documentation or how do i have to install your modules ?
Regards Markus

**Comment by sachaboudjema** [comment]
Hi Markus,

I added installation notes to the README on the master branch.
Note that just published the modules to Ansible Galaxy, which provides an easy way to install the modules.

If you need any further help using the modules, I created a google group for general discussions and help: https://groups.google.com/forum/#!forum/ansible-modules-arubaos
